### ISSUE TITLE
Other users are not allowed to list their token

### ISSUE THREAD

**Issue by byteblock-labs** [tqtezos/minter-sdk#176]
We have used openminter code to create NFT marketplace. Openminter is using there contracts:
  Fa2MultiNftAssetCode,
  Fa2MultiNftFaucetCode
  FixedPriceSaleMarketTezCode,
  FixedPriceSaleTezFixedFeeCode
One weird issue we are facing. The account which has deployed the contract can mint and sell the tokens. Other users can just mint the token. They are not able to list for SELL.  The issue is encountered "NOT_AN_ADMIN". 
![Capture](https://user-images.githubusercontent.com/75021199/121283718-38c86080-c8f9-11eb-8be1-892aba8c2f00.PNG)
contract details:
"nftFaucet": "KT1Dx9zAXbP5jFZNeLx176DVZUtGDrDpwH3X",
		"marketplace": {
			"fixedPrice": {
				"tez": "KT1LNfFkc8vkgMB6xpMDeGTNNo6Ds9VLmZ4x"
			}
		}
how can we enable other users to sell their minted stuff?

**Comment by EGuenz** [comment]
You have two options: 

1. You can originate the FixedPrice contract without an Admin. If that is done any user should be able to sell. 
2. You can also use `FixedPriceSaleMarketTezFixedFeeCancelOnlyAdmin` or `FixedPriceSaleMarketTezCancelOnlyAdmin`for versions of the fixed price contract that has an Admin whose only power is to cancel sales they don't want listed on the contract. Otherwise, any user can sell. 

Hope that helps.
