### ISSUE TITLE
Create PR template for smart contract submission

### ISSUE THREAD

**Issue by zachrbrown** [tqtezos/minter-sdk#69]
Provide a checklist and basic sanity checks with which smart contract developers may assess whether or not their contract is ready to be reviewed.

Should include things like (among others):
- Does the contract implement admin checks
- Is the contract being tested against arbitrary values
- Does it include property-based tests

**Comment by michaeljklein** [comment]
- [ ] Is each entrypoint and storage field documented?
- [ ] Are there property tests for each entrypoint?
  + [ ] Is there a succeeding example for each?
  + [ ] Is there a failing example for each?
    * [ ] If no failure is possible without an out-of-gas or other protocol-level error, is there a property test asserting this?
  + [ ] When using `cleveland`, are some test cases generated using `Arbitrary`?
- [ ] Is there an integration test for each happy path in the docs, i.e. for each documented feature?
- [ ] Administrator tests:
  + [ ] Vs. unknown address
  + [ ] Vs. known address
  + [ ] Vs. contract's own address (`SELF_ADDRESS`)
  + [ ] Can any administrators be updated?
- [ ] Token lifecycle:
  + [ ] If your contract accepts Tez, is it always possible to transfer those Tez out of the contract?
  + [ ] If your contract holds a FA2 token, is it always possible to transfer the entire balance out of the contract?

**Comment by pasqu4le** [comment]
Some additions that may be useful to the list above:
[ ] Administrator tests:
    [ ] Can any administrators be updated?
        [ ] are new administrators required to confirm their role?
        [ ] do new administrators replace the current ones?
            [ ] do current administrator retain their privilege until new administrators are confirmed?
[ ] are there strict structures (`list`,`set`, `map`) that can grow in the storage?
    [ ] can their size grow without moderation?
        [ ] is there a limit to how much they can grow?
            [ ] is this tested to maintain entrypoints execution's gas cost acceptable?
[ ] does the contract interact with other ones?
    [ ] are there `view` entrypoints and/or can the contract call one of it's own entrypoints?
        [ ] are there tests to cover the possibility of your contract calling itself?
    [ ] are there tests for complex interactions and failures in called contracts?

The following are less safety oriented, but may be good to have anyway:
[ ] are all storage fields annotated?
[ ] are all errors/failures documented?
[ ] is the contract FA2 compliant?
    [ ] does it comply with optional requirements as well?
[ ] does the contract support TZIP-16 metadata?
    [ ] is an example/template metadata provided?


Lastly I would suggest to put these as affirmations, not questions, and specify that they can be checked when not applying.
This way for example a contract PR without administration can check the relative box without reviewers turning away because of it, and let these decide if that was justified or not.

**Comment by Martoon-00** [comment]
Regarding the administrator functionality, I've already [added](https://github.com/tqtezos/minter-sdk/blob/martoon/swap-contract-whitelisted/packages/minter-contracts/test-hs/test/Test/NonPausableSimpleAdmin.hs) Cleveland tests on a two-phase update functionality, and these tests can be reused for various contracts.

So maybe instead of enlisting specific tests required for admin functionality, we better make sure that there is a test component that covers all the desired points (after my PR is merged), and refer to this test component in the template?

**Comment by Martoon-00** [comment]
- [ ] Are all paths of the implemented contracts/modules covered with tests? 
  _This is a pretty generic one, but I believe it is very suitable here. Reviewers should check whether all necessary tests are indeed present. Note that this touches not only happy paths, we already have some tests on happy paths and it didn't help us much._
* UX compliance:
  - [ ] If for some error 
    1. reason of the failure is not clear for the user;
    2. error details are difficult to derive off-chain;
    Then this error is accompanied by all the necessary error details. 

    Bad: `INSUFFICIENT_BALANCE`
    Good: `(INSUFFICIENT_BALANCE, (<required>, <present>))`.
    _This is worth discussing. For instance, FA2 does not follow this practice :see_no_evil:_
* CI checks
  - [ ] My contract is included into the list of contracts compiled by CI.
  - [ ] Tests on my contract are executed by CI.

**Comment by kkirka** [comment]
wrt. security checks:
- [ ] There are no authorization flaws:
  - [ ] Doesn't use `source` for authorization
  - [ ] Uses tickets in case a sender can be tricked into issuing a malicious request
- [ ] Does not use [Michelson anti-patterns](https://tezos.gitlab.io/developer/michelson_anti_patterns.html)
- [ ] Uses semaphores (preferrable) or mutexes (acceptable) in case of expected reentrancy like receiving a result of a `view` call
- [ ] Works in both BFS and DFS execution order _(We can change this after Florence is out)_

**Comment by dani-jozsef** [comment]
> Token lifecycle:
>     If your contract accepts Tez, is it always possible to transfer those Tez out of the contract?
>     If your contract holds a FA2 token, is it always possible to transfer the entire balance out of the contract?

I kinda dislike the wording of this.

It makes it sound like these are requirements, when in fact, in most cases, not only do you not want it to "always" be possible to do this, but rather if it's possible under any circumstance, the contract is considered compromised.

For example, in DeFi, you want both of these operations to be impossible for anyone ever.

**Comment by michaeljklein** [comment]
@dani-jozsef These requirements are meant to emphasize that it's _possible_ for tokens to exit the contract, i.e. it's not a "token black hole," unlike a common "sink" contract used for testing: `parameter unit; storage unit; code {CDR; NIL operation; PAIR}`. The term "transfer" is used since `TRANSFER_TOKENS` must be called by the contract, not because the caller can control how many tokens/when/to whom/etc. Most contracts disallow arbitrary transfers of their tokens and, as you point out, complex restrictions on transfers are especially common in DeFi.

A contract is a _black hole_ for a particular kind of token if there does _not_ exist a series of contract calls that result in a token balance of zero. It is impossible to fully divest from, upgrade, or migrate such a contract. One could argue that tokens that enter a black hole contract actually leave the network, even if some "wrapped" or other kind of derivative tokens are produced.

This can be difficult to enforce because contracts restrict transfers in arbitrary ways:
- A contract may only allow transfers with an upgrade, e.g. a DAO that only allows transfers of its balance as part of an upgrade
- A contract might only allow transfers that are validated by some external contract, e.g. the [Transferlist contract](https://github.com/tqtezos/lorentz-contract-transferlist)
  * We don't want to consider the contract a black hole if a misconfigured Transferlist contract could block all transfers
- A contract could accept any amount of tokens, but only allow transferring out a multiple of some constant `n`
  * E.g. the [vesting contract](https://github.com/tqtezos/vesting-contract)
  * In this case, you need to send `n - mod(balance, n)` Tez to the contract to get the balance to zero
- A contract could accept only multiples of `n` but only transfer out multiples of `m`, where `gcd(n, m) = 1` and `n > m`, e.g. `n = 3, m = 2`
  * All tokens transferred in can exit the contract, but the balance can never be zero once the balance is a multiple of `3`
  * This could be temporary if `n, m` are chosen by a DAO or other oracle

I've updated the wording in my checklist above.

**Comment by dani-jozsef** [comment]
I think we might disagree on some philosophical topics here. Black hole contracts do have valid use cases - such as "burning" a token for purpose of transferring value to another blockchain -, and I consider it to not be the contract developer's job to protect people from themselves.

If you send an unhandled token to a contract, it's lost. That's all there is to it, and it's not the job of the blockchain or the contract to prevent that. The alternative just introduces too many possible vulnerabilities. If anyone has the ability to withdraw arbitrary tokens from a contract, it might become a backdoor to maliciously defund it.

As for divesting from a contract or upgrading it, those are only valid use cases if the contract represents a _centralized_ entity. Some contracts do, but many do not. Even those deployed by centralized legal entities are often intended as independent, uncontrollable / unstoppable / unchangeable entities, for reasons philosophical and legal (eg. to make sure that the deploying legal entity or person won't be considered a financial service provider by authorities).
